# Generated by Django 3.0 on 2019-12-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(help_text='Enter Student ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('sir_name', models.CharField(help_text='Enter Sir Name', max_length=20)),
                ('other_name', models.CharField(help_text='Enter Other Name', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('kcpe_marks', models.IntegerField(blank=True, null=True)),
                ('primary_school', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('is_enrolled', models.BooleanField(default=True)),
                ('home_county', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_town', models.CharField(blank=True, help_text='Enter home Town', max_length=20, null=True)),
                ('health', models.TextField(blank=True, default='Good', help_text='Enter health status or complications', max_length=500, null=True)),
                ('emergency_contact_name', models.CharField(max_length=40)),
                ('emergency_phone', models.IntegerField(help_text='Enter Emergency phone number')),
                ('emergency_email', models.CharField(help_text='Enter email', max_length=20)),
                ('father_alive', models.BooleanField(blank=True, default=True, help_text='Is the father alive?')),
                ('mother_alive', models.BooleanField(blank=True, default=True, help_text='Is the mother alive?')),
            ],
            options={
                'ordering': ['sir_name', 'first_name'],
            },
        ),
    ]
