# Generated by Django 3.0.1 on 2019-12-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='premium',
        ),
        migrations.AddField(
            model_name='father',
            name='premium',
            field=models.BooleanField(blank=True, default=False, help_text='Do not edit this'),
        ),
        migrations.AddField(
            model_name='mother',
            name='premium',
            field=models.BooleanField(blank=True, default=False, help_text='Do not edit this'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='premium',
            field=models.BooleanField(blank=True, default=False, help_text='Do not edit this'),
        ),
    ]
