# Generated by Django 3.0 on 2019-12-17 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Father',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the first name of the student's male guardian", max_length=20)),
                ('sir_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter the first name of the student's female guardian", max_length=20)),
                ('sir_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='First name of sponsor if applicable', max_length=20, null=True)),
                ('sir_name', models.CharField(blank=True, help_text='Sir name of sponsor if applicable', max_length=20, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Only if the Sponsor is a company', max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='emergency_email',
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_relationship',
            field=models.CharField(help_text='Eg: Close Uncle', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='premium',
            field=models.BooleanField(blank=True, default=False, help_text='Do not edit this'),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=True, help_text='Is the student enrolled?'),
        ),
        migrations.AddField(
            model_name='student',
            name='father',
            field=models.ForeignKey(help_text="Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Father'),
        ),
        migrations.AddField(
            model_name='student',
            name='mother',
            field=models.ForeignKey(help_text="Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Mother'),
        ),
    ]
