# Generated by Django 3.0 on 2019-12-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20191217_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sponsor',
            field=models.ForeignKey(help_text="(IF APPLICABLE ONLY) Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Sponsor'),
        ),
    ]
