# Generated by Django 3.0 on 2019-12-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='father',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother',
        ),
        migrations.AddField(
            model_name='student',
            name='female_guardian',
            field=models.ForeignKey(help_text="Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Mother'),
        ),
        migrations.AddField(
            model_name='student',
            name='male_guardian',
            field=models.ForeignKey(help_text="Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Father'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sponsor',
            field=models.ForeignKey(help_text="(IF APPLICABLE ONLY) Select or Enter the details of the student's male guardian", null=True, on_delete=django.db.models.deletion.PROTECT, to='students.Sponsor'),
        ),
    ]
