# Generated by Django 3.0 on 2019-12-17 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0004_auto_20191217_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.Classes'),
        ),
    ]
