# Generated by Django 3.0.1 on 2019-12-20 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20191219_1210'),
        ('students', '0004_auto_20191220_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='classNumeral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.ClassNumeral'),
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.Stream'),
        ),
    ]
