# Generated by Django 3.0.1 on 2019-12-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20191220_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='class_stream',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classNumeral',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stream',
        ),
    ]
