# Generated by Django 3.0.1 on 2019-12-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20191221_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='class_stream',
            new_name='Class',
        ),
    ]
