# Generated by Django 3.0.1 on 2019-12-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20191221_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Class',
            new_name='class_ns',
        ),
    ]
