# Generated by Django 3.0 on 2019-12-17 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20191217_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingstaff',
            name='staff_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='staff.Staff'),
        ),
    ]
