# Generated by Django 3.0.1 on 2019-12-18 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000000), django.core.validators.MinValueValidator(10000)])),
                ('class_numeral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.ClassNumeral')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_motto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeePaymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2000000), django.core.validators.MinValueValidator(10000)])),
                ('fee_payable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.FeePayable')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
