# Generated by Django 3.0 on 2019-12-17 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_auto_20191217_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('school_motto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FeePayable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee', models.IntegerField()),
                ('class_numeral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.ClassNumeral')),
            ],
        ),
    ]
