# Generated by Django 3.0.1 on 2019-12-19 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepayable',
            options={'ordering': ['class_numeral', 'total_fee'], 'verbose_name_plural': 'Fee Payable'},
        ),
        migrations.AlterModelOptions(
            name='feepaymentstatus',
            options={'ordering': ['fee_paid', 'student'], 'verbose_name_plural': 'Fee Payment Status'},
        ),
    ]
