# Generated by Django 3.0.1 on 2019-12-18 09:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassNumeral',
            fields=[
                ('name', models.IntegerField(help_text='For Example: 1,2,3. Streams (eg; east) will be added later', primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name_plural': 'Class Numerals',
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('name', models.CharField(help_text='For Example: East, Yellow, e.t.c', max_length=15, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjectHODs', to='staff.TeachingStaff')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actively_teaching', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.TeachingStaff')),
            ],
            options={
                'ordering': ['subject', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_graduation', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3500), django.core.validators.MinValueValidator(2020)], verbose_name='Year of Graduation ')),
                ('active', models.BooleanField(default=False)),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.ClassNumeral')),
                ('assistant_class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes_assistantClassTeachers', to='staff.TeachingStaff')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classTeachers', to='staff.TeachingStaff')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Stream')),
            ],
            options={
                'verbose_name_plural': 'Classes',
                'ordering': ['Class', 'stream'],
            },
        ),
    ]
