# Generated by Django 3.0.1 on 2019-12-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['Class', 'stream'], 'verbose_name_plural': 'Class + Streams (Normal Classes)'},
        ),
    ]
