# Generated by Django 3.0.1 on 2019-12-19 11:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20191218_1632'),
        ('staff', '0001_initial'),
        ('academics', '0003_auto_20191218_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: 2019 End Term 1 Exam', max_length=50)),
                ('term', models.CharField(choices=[('o', 'one'), ('tw', 'two'), ('th', 'three')], max_length=4)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3500), django.core.validators.MinValueValidator(2020)])),
                ('exam_start_date', models.DateField()),
                ('classes_involved', models.ManyToManyField(to='academics.ClassNumeral')),
                ('subjects', models.ManyToManyField(help_text='Select Subjects', to='academics.Subject')),
            ],
            options={
                'ordering': ['year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectTeacherClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Classes')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.SubjectTeacher')),
            ],
            options={
                'ordering': ['Class', 'teacher'],
            },
        ),
        migrations.CreateModel(
            name='ExamPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Club, Society or Organisation Name', max_length=20)),
                ('purpose', models.TextField(blank=True, max_length=30, null=True)),
                ('more_information', models.TextField(blank=True, max_length=100, null=True)),
                ('members', models.ManyToManyField(help_text='Select Student Members', to='students.Student')),
                ('teacher_assistant_lead', models.ManyToManyField(help_text='Select assistant Teacher', related_name='Assistant_Teacher_Leads', to='staff.TeachingStaff')),
                ('teacher_lead', models.ManyToManyField(help_text='Select Teacher In Charge', related_name='Teacher_Leads', to='staff.TeachingStaff')),
            ],
            options={
                'ordering': ['name', 'purpose'],
            },
        ),
    ]
