# Generated by Django 3.0.1 on 2019-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_club_exam_examperformance_subjectteacherclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Example: End Term ', max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.CharField(choices=[('Term Two', 'Term One'), ('Term Two', 'Term Two'), (' Term Three', ' Term Three')], max_length=11),
        ),
    ]
