# Generated by Django 3.0.1 on 2019-12-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20191219_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='examperformance',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('A', 'D'), ('E', 'E'), ('F', 'F'), ('Z', 'Z')], max_length=1, null=True),
        ),
    ]
