# Generated by Django 3.0.1 on 2019-12-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_examperformance_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'ordering': ['class_numeral', 'stream'], 'verbose_name_plural': 'Class + Streams (Normal Classes)'},
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='Class',
            new_name='class_numeral',
        ),
    ]
