# Generated by Django 3.0.1 on 2019-12-21 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_auto_20191221_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('student_id', models.IntegerField(help_text='Enter Student ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('sir_name', models.CharField(help_text='Enter Sir Name', max_length=20)),
                ('other_name', models.CharField(help_text='Enter Other Name', max_length=20)),
                ('father_alive', models.BooleanField(default=True, help_text='Is the father alive?', null=True)),
                ('mother_alive', models.BooleanField(default=True, help_text='Is the mother alive?', null=True)),
                ('father_first_name', models.CharField(help_text="Enter the first name of the student's male guardian", max_length=20, null=True)),
                ('father_sir_name', models.CharField(max_length=20, null=True)),
                ('father_email', models.EmailField(max_length=254, null=True)),
                ('father_phone', models.IntegerField(null=True)),
                ('father_premium', models.BooleanField(blank=True, default=False, help_text='Do not edit this')),
                ('mother_first_name', models.CharField(help_text="Enter the first name of the student's female guardian", max_length=20, null=True)),
                ('mother_sir_name', models.CharField(max_length=20, null=True)),
                ('mother_email', models.EmailField(max_length=254, null=True)),
                ('mother_phone', models.IntegerField(null=True)),
                ('mother_premium', models.BooleanField(blank=True, default=False, help_text='Do not edit this')),
                ('sponsor_first_name', models.CharField(blank=True, help_text='First name of sponsor if applicable', max_length=20, null=True)),
                ('sponsor_sir_name', models.CharField(blank=True, help_text='Sir name of sponsor if applicable', max_length=20, null=True)),
                ('sponsor_company_name', models.CharField(blank=True, help_text='Only if the Sponsor is a company', max_length=20, null=True)),
                ('sponsor_premium', models.BooleanField(blank=True, default=False, help_text='Do not edit this')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=6)),
                ('kcpe_marks', models.IntegerField(blank=True, null=True)),
                ('primary_school', models.CharField(blank=True, max_length=20, null=True)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('is_enrolled', models.BooleanField(default=True, help_text='Is the student enrolled?')),
                ('home_county', models.CharField(blank=True, help_text='Enter home County', max_length=20, null=True)),
                ('home_town', models.CharField(blank=True, help_text='Enter home Town', max_length=20, null=True)),
                ('religion', models.CharField(blank=True, max_length=10, null=True)),
                ('health', models.TextField(blank=True, default='Good', help_text='Enter health status ', max_length=500, null=True)),
                ('year_of_graduation', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3500), django.core.validators.MinValueValidator(2020)], verbose_name='Year of Graduation ')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'student_class_stream_view',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='StudentClassStreamView',
        ),
        migrations.RenameField(
            model_name='examperformance',
            old_name='student',
            new_name='stud',
        ),
    ]
