# Generated by Django 3.0.1 on 2019-12-21 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_auto_20191221_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='id',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_id',
            field=models.CharField(default=0.7287406219844453, max_length=50, primary_key=True, serialize=False),
        ),
    ]
