# Generated by Django 3.0.1 on 2019-12-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_auto_20191221_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_id',
        ),
        migrations.AddField(
            model_name='exam',
            name='id',
            field=models.CharField(default=0.5795339257396083, max_length=50, primary_key=True, serialize=False),
        ),
    ]
