# Generated by Django 3.0.1 on 2019-12-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_auto_20191221_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.CharField(default=0.8508369980444352, max_length=50, primary_key=True, serialize=False),
        ),
    ]
