# Generated by Django 3.0.1 on 2019-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_auto_20191221_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
