# Generated by Django 3.0.1 on 2019-12-26 09:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_auto_20191222_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examperformance',
            name='biology',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='business',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='chemistry',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='english',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='geography',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='history',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='kiswahili',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='mathematics',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='physics',
        ),
        migrations.AddField(
            model_name='examperformance',
            name='subject_marks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Subject', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
