# Generated by Django 3.0.1 on 2019-12-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_auto_20191226_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examperformance',
            old_name='name',
            new_name='exam_name',
        ),
    ]
