# Generated by Django 3.0.1 on 2019-12-26 09:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_auto_20191226_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='examperformance',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.Subject'),
        ),
        migrations.AlterField(
            model_name='examperformance',
            name='subject_marks',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
