# Generated by Django 3.0.1 on 2019-12-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_auto_20191226_1009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamPerformanceView',
        ),
    ]
