# Generated by Django 3.0.1 on 2019-12-26 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_delete_examperformanceview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPerformanceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_marks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('Z', 'Z'), ('Y', 'Y')], max_length=2, null=True)),
                ('first_name', models.CharField(help_text='Enter First Name', max_length=20)),
                ('sir_name', models.CharField(help_text='Enter Sir Name', max_length=20)),
            ],
            options={
                'db_table': 'exam_performance_view',
                'managed': False,
            },
        ),
    ]
