# Generated by Django 3.0.1 on 2019-12-28 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_examperformanceview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examperformance',
            old_name='subject_marks',
            new_name='english',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='examperformance',
            name='subject',
        ),
        migrations.AddField(
            model_name='examperformance',
            name='kiswahili',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='mathematics',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='religious_education',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='science',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='social_studies',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examperformance',
            name='total',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(500), django.core.validators.MinValueValidator(0)]),
        ),
    ]
